basePath: /
definitions:
  dtos.CreateUserInput:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - name
    - password
    type: object
  dtos.JWTTokenOutput:
    properties:
      token:
        type: string
    type: object
  dtos.LoginInput:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  dtos.UpdateUserInput:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        minLength: 6
        type: string
    type: object
  dtos.UsersListOutput:
    properties:
      page:
        type: integer
      per_page:
        type: integer
      users:
        items:
          $ref: '#/definitions/entity.User'
        type: array
    type: object
  entity.User:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  errors.CustomError:
    properties:
      error:
        type: string
    type: object
  errors.ValidationError:
    properties:
      error:
        type: string
      key:
        type: string
    type: object
host: localhost:8001
info:
  contact: {}
  description: User API with authentication
  title: Go User's API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login an user
      parameters:
      - description: Login Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.JWTTokenOutput'
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/errors.ValidationError'
            type: array
        "401":
          description: Unauthorized
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.CustomError'
      summary: Login an user
      tags:
      - login
  /users:
    get:
      description: list all users
      parameters:
      - description: page number
        in: query
        name: page
        type: string
      - description: items per page number
        in: query
        name: perPage
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.UsersListOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.CustomError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.CustomError'
      security:
      - ApiKeyAuth: []
      summary: list all users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: create an user
      parameters:
      - description: user request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.CreateUserInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entity.User'
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/errors.ValidationError'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.CustomError'
      security:
      - ApiKeyAuth: []
      summary: create an user
      tags:
      - users
  /users/{id}:
    delete:
      description: delete an user
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.CustomError'
      security:
      - ApiKeyAuth: []
      summary: delete an user
      tags:
      - users
    get:
      description: get an user
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/errors.CustomError'
            type: array
        "404":
          description: Not Found
      security:
      - ApiKeyAuth: []
      summary: get an user
      tags:
      - users
    put:
      consumes:
      - application/json
      description: update an user
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: string
      - description: Update user request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.UpdateUserInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/errors.ValidationError'
            type: array
      security:
      - ApiKeyAuth: []
      summary: update an user
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
